### ISSUE TITLE
can guid impl be changed?

### ISSUE THREAD

**Issue by websvcPT** [fastapi-users/fastapi-users-db-sqlalchemy#10]
Hi there,
While testing fastapi-users [sqlalchemy] along with [sqladmin](https://github.com/aminalaee/sqladmin) I bumped on this

```bash
  File "/mnt/1T/work/user-management/.venv/lib/python3.8/site-packages/sqladmin/forms.py", line 78, in get_converter
    raise Exception(  # pragma: nocover
Exception: Could not find field converter for column id (<class 'fastapi_users_db_sqlalchemy.guid.GUID'>).
```
I understand that sqladmin does not know how to handle this since it does not have converter for `UUIDChar` (https://github.com/aminalaee/sqladmin/blob/main/sqladmin/forms.py#L78). It does handle `UUID` though.

This is provoqued by the following line at fastapi-users-db-sqlalchemy/
https://github.com/fastapi-users/fastapi-users-db-sqlalchemy/blob/3e537753fb13626e56291069a417d8793a492685/fastapi_users_db_sqlalchemy/guid.py#L18

.venv/lib/python3.8/site-packages/fastapi_users_db_sqlalchemy/guid.py
![image](https://user-images.githubusercontent.com/1758961/161014198-5e853f6a-8e43-47ba-9f0e-86901ee35da2.png)

Is `impl = UUIDChar` a "standard" implementation or it should be named `impl = UUID` instead?

Otherwise, any way can I overwrite this?

**Comment by frankie567** [comment]
Actually, `UUIDChar` is defined just above. The rationale about why it's like this is here: https://github.com/fastapi-users/fastapi-users/issues/646 In a nutshell, some libraries need to have the `python_type` explicitly defined to work.

I think it's more an issue on `sqladmin` side: overloading an `impl` is quite common and I believe they should support this case. For example, on `pydantic-sqlalchemy`, they take care of looking for a `python_type` everywhere: https://github.com/tiangolo/pydantic-sqlalchemy/blob/8667e213a6ad8e62288fad2a6621958e8ab0b688/pydantic_sqlalchemy/main.py#L25-L29

**Comment by websvcPT** [comment]
Thanks for your clarification @frankie567 :metal:
