### ISSUE TITLE
_get_user() fails when no user in db

### ISSUE THREAD

**Issue by kamikaze** [fastapi-users/fastapi-users-db-sqlalchemy#11]
```python
    async def _get_user(self, statement: Select) -> Optional[UP]:
        results = await self.session.execute(statement)
        user = results.first()
```

fails at `.first()` when there is no records in user table and then results is None

**Comment by frankie567** [comment]
Could you give the error stack trace you're getting? I'm not sure to see what the problem is.

**Comment by kamikaze** [comment]
the problem is: when user table is empty you get None in results variable.

**Comment by frankie567** [comment]
I cannot reproduce the problem on my side: when the table is empty, `_get_user` returns `None` without error. Could you give me:

* The DBMS you're using (PostgreSQL, MySQL...)
* The associated driver (asyncpg, aiomysql...) and its version
* The version of SQLAlchemy
